### ISSUE TITLE
[Voorbeeld]  z-waarde van Pand dient nader gespecificeerd te worden

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/IMBAG#1]
Document: 20161010_BAG_gegevenscatalogus_concept_v0.4.pdf, paragraaf 3.3.1 blz. 9

Samenvatting: 
[Voorbeeld] z-waarde van Pand niet gespecificeerd

Beschrijving: 
[Voorbeeld] In de catalogus staat nu niets opgenomen over waar de z-waarde van een Pand aan gerelateerd is: hoogste punt, gemiddelde dakhoogte, of ...

Oplossingsrichting:
[Voorbeeld] In catalogus nader de z-waarde van een Pand specificeren, namelijk gemiddelde dakhoogte.

**Comment by lodewijkjessen** [comment]
@FrankKooij test

**Comment by IMBAG** [comment]
@FrankKooij @lodewijkjessen test
