### ISSUE TITLE
Aanpassing unieke aanduiding van alle objecttypen in de BAG als gevolg van het nieuwe IMBAG

### ISSUE THREAD

**Issue by Debatse** [Geonovum/IMBAG#10]
De unieke aanduiding van alle objecttypen in de BAG wordt in IMBAG aangepast, dus voor PAND, VERBLIJFSOBJECT, LIGPLAATS, NUMMERAANDUIDING etc etc. Dit heeft grote consequenties niet alleen voor BAG applicaties zelf maar ook voor alle andere applicaties die verwijzen naar een object uit de BAG. Geonovum en Kadaster die het nieuwe IMBAG opstellen vinden dit geen probleem. Graag wil ik van gemeenten en leveranciers weten hoe zij hier in zitten. Ook voor de basisregistraties zoals de BRWOZ en NHR e.d. zullen de nodige aanpassingen vereist zijn.

**Comment by rindertdijkstra** [comment]
Onacceptabel. Als er iets vast moet blijven staan is het wel de primaire sleutel.

**Comment by ArjanKloosterboer** [comment]
De vraag is waarom de (al unieke) identificatie, van een object in de BAG, voorafgegaan moet worden door een, voor elk objecttype (Pand, Verblijfsobject, etc_), zelfde aanduiding (de 'namespace')? Alle objecten hebben primair bestaansrecht binnen de BAG; van elk object is bekend dat het tot het BAG-domein behoort. Zo lang deze objecten gebruikt worden binnen dat domein is de namespace niet nodig. Alleen als een BAG-object in bredere context, maar dan als Geo-object, gebruikt zou worden, dus zonder dat bekend is dat het een object van het BAG-domein betreft, is die namespace nodig. Daarvan is hier geen sprake: het gaat hier om de catalogus voor het BAG-domein, dat is in de voorgaande hoofdstukken duidelijk vermeld. Die namespace is als onderdeel van de identificatie m.i. dan ook niet nodig. Voor hergebruik van de BAG-objecten als generieke geo-objecten kan volstaan worden met een afspraak cq. regel in de catalogus dat de identificatie van een dergelijk geo-object bestaat uit de BAG-identificatie van het object vooraf gegaan door genoemde namespace.
