### ISSUE TITLE
Opname van BAG object in IM?

### ISSUE THREAD

**Issue by Debatse** [Geonovum/IMBAG#13]
De definitie van objecttype BAG-object is als volgt 
‘De gemeenschappelijke eigenschappen van een BAG-object’.
In BGT komen we een soortgelijke definitie voor het objecttype IMGeo object tegen.
‘De gemeenschappelijke eigenschappen van een grootschalig topografisch object, al dan niet uit de basisregistratie’.
Met beide definities kan ik niets Beiden definiëren ze niet wat een BAG-object is of wat een IMGeo object is. M.a.w. op basis van deze definities kan niet vast gesteld worden tot welk objecttype een ding uit de werkelijkheid behoort. 

Reden dat het BAG-object is opgenomen is het feit dat het BAG object  zuiver een technische constructie is om ervoor te zorgen dat een aantal eigenschappen eenmalig gespecificeerd kunnen worden. Volgens mij nemen we dat niet op in een semantisch informatiemodel

**Comment by rindertdijkstra** [comment]
Het objecttype BAG-Object is geen objecttype. Dat blijkt al uit de definitie: de gemeenschappelijke eigenschappen van een BAG-object. Dat is geen (definitie van een) objecttype. Zeg mij hoe ik een BAG-object in de werkelijkheid kan herkennen. 
Voor semantische modellering zou je gebruik kunnen maken van een methode zoals ORM. Als er al sprake is van een echte generalisatie/specialisatie dan komt die wel tevoorschijn. ORM kun je redelijk rechttoe rechtaan omzetten naar UML.

**Comment by rindertdijkstra** [comment]
Stel je voor dat we besluiten om de BAG en de BGT samen te voegen. Is een BAG-object dan een specialisatie van een IMGeo-object, of staan ze naast elkaar en zet je er nog een objecttype boven?
Dus: modelleer wat je wilt communiceren over objecten in de werkelijkheid. Dat kunnen naast concrete objecten, zoals PAND, overigens ook conceptuele objecten zijn zoals een OVEREENKOMST.

**Comment by Debatse** [comment]
Rindert in de BAG en BGT die beiden onderdeel uitmaken van het stelsel van basisregistraties komen we nu al onder meer het objecttype Pand tegen. En zoals nu wordt  voorgesteld door het programma 'Op weg naar BAG2.0', is Pand een specialisatie van een BAG-object maar is Pand ook een specialisatie van een IMGeo object. Bovendien heeft een Pand in de BGT (let op: ook al in de huidige situatie!) een andere unieke aanduiding dan in de (IM)BAG.

De introductie van het BAG object is vanuit semantisch oogpunt niet verantwoord en zeker niet vanuit de optiek van een stelsel van basisregistraties.

**Comment by rindertdijkstra** [comment]
Het is erg jammer dat het gegevensmodel van de BGT geen semantisch model is, maar uitgaat van de representatie op de kaart. Het is daarom ook een slecht idee om BAG 2.0 op dezelfde leest te schoeien als de BGT. Verbeter liever het BGT-model door er een semantisch model van te maken. Dan heb je ook geen van de BAG afwijkende identificatie van een PAND nodig.
