### ISSUE TITLE
voorgestelde IMBAG is geen semantisch model

### ISSUE THREAD

**Issue by rindertdijkstra** [Geonovum/IMBAG#15]
Het IMBAG model is geen semantisch model. In een semantisch model ga je niet gegevenstypen die op elkaar lijken in een verzonnen objecttype plaatsen. Je modelleert wat je wilt communiceren over de werkelijkheid en dat doe je inrichtingsonafhankelijk. Normaliseren en optimaliseren doe je in een logisch of technisch model.  

Het objecttype BAG-Object is geen objecttype. Dat blijkt al uit de definitie: de gemeenschappelijke eigenschappen van een BAG-object. Dat is geen (definitie van een) objecttype.

Een Woonplaats is geen specialisatie van een BAG-Object. Dan zou de definitie ongeveer moeten luiden: een Woonplaats is een BAG-object die...... Een Woonplaats is ook geen feature zijnde een punt, lijn of vlak. Wat een vreselijke degradatie zou dat zijn. De BAG-catalogus definieert de Woonplaats als Een WOONPLAATS is een door het bevoegde gemeentelijke orgaan als zodanig aangewezen en van een naam voorzien gedeelte van het grondgebied van de gemeente.

Iets dergelijks geldt voor een PAND. Een Pand is ook geen vlak. En een PAND is ook geen specialisatie van een BAG-object. Een PAND-identificatie en een Woonplaats identificatie zijn niet hetzelfde gegevenstype.

Een MAN is een specialisatie van een NATUURLIJK PERSOON, een VROUW is een specialisatie van een NATUURLIJK PERSOON, ik identificeer ze allebei met het BSN. 

Het zal duidelijk zijn. Ik vind de voorgestelde modellering niet acceptabel, laat staan de aanpassing van de wijze van identificeren.

**Comment by Debatse** [comment]
Helemaal mee eens. Het IMBAG bevat duidelijke implementatie aspecten zoals onder meer de opname van het BAG-object, de naamgeving van attributen en relaties in camelcase en de opname van inOnderzoek als attribuut. Deze horen niet thuis in een semantisch model!

inOnderzoek is duidelijk een metagegeven van een attribuut/ relatie. Het zegt iets over de waarde van het attribuut. inOnderzoekis op semantische niveau geen kenmerk / eigenschap van een Pand of Woonplaats.

**Comment by rindertdijkstra** [comment]
Voor alle duidelijkheid: ik vind het belangrijk dat het gegevensmodel zoals verwoord in de originele gegevenscatalogus blijft bestaan. Als Kadaster ervoor kiest om de BAG-registratie op een bepaalde manier technisch vorm te geven is daar niets op tegen mits de BAG-gegevens gewoon geleverd kunnen worden conform de originele BAG-gegevenscatalogus. Kadaster moet dan dus de match kunnen maken van de technische realisatie naar het originele gegevenswoordenboek en gewoon de BAG-gegevens conform dit gegevenswoordenboek blijven leveren. Een wijziging hierin is niet acceptabel. IMBAG bestempelen als semantisch gegevensmodel is geen goed idee.
