### ISSUE TITLE
Schuurtjes in de tuin

### ISSUE THREAD

**Issue by Dorrestijn** [Geonovum/IMBAG#2]
Document: Hoofdstuk __: Objectafbakening (pandafbakening, punt 4)

Samenvatting: 
Voorwaarden uit oude objectenhandboek niet genoemd in nieuw document

Beschrijving: 
In het oude objectenhandboek moest een schuurtje aan één van deze vier voorwaarden voldoen: vergunningsplichtig, gemaakt van steen, eigen fundering of deel uitmakend van oorspronkelijk bouwplan. In de nieuwe beschrijving vind ik die niet terug. Er wordt nu vooral gekeken naar caravans. Veel zelf getimmerde schuurtjes in de achtertuinen zijn niet verplaatsbaar en zouden nu wel opgenomen moeten worden.

Oplossingsrichting:
Geef duidelijk aan of houten schuurtjes wel of niet in de BAG opgenomen moeten worden. Nu wordt enkel over kassen gesproken.

**Comment by lodewijkjessen** [comment]
We (de opstellers) lichten dit graag toe.
Als hoofdregel staat in het Objectenhandboek (OHB) in par. 2.3.3.: 
_Vrijstaande_ _schuren worden soms wel en soms niet als pand afgebakend. Een schuur die naar aard en inrichting bestemd zijn om duurzaam ter plaatse te blijven, wordt wel als pand afgebakend; een schuur waarbij dat niet het geval is, wordt niet als pand afgebakend. 
Dat betekent dat een vrijstaande schuur in elk geval wel als pand wordt afgebakend als: (volgt een opsomming van criteria)._
Wij beschouwen deze tekst uit het OHB als een toelichting op de panddefinitie ten aanzien van schuren die met name tijdens de opbouw van de BAG nuttig was. Tegelijk is de essentie dat een schuur een pand is als die aan de panddefinitie voldoet. De achtergrond van het niet langer opnemen van een afzonderlijke tekst ten aanzien van schuren is dus dat voor de afbakening van schuren geen bijzonderheden gelden ten aanzien van panden in het algemeen.

**Comment by PieterBs** [comment]
Vergunnigsvrije bouwwerken zijn lastig op te sporen, daarnaast als ze eenmaal inzichtelijk zijn gemaakt, bijvoorbeeld met een luchtfoto vergelijk, dan is het nog moeilijk om te bepalen over wat voor een soort objecten we het hebben.

**Comment by marleenhermans** [comment]
Eens met Pieter; maar ook de oorspronkelijk geplaatste schuren. In de BAG zijn soms vervelend...omdat vroeger veel vergunningen voor zijn afgegeven (was binnen afstand van 1 m van de erfscheiding vergunningplichtig), zijn er veel schuurtjes in de BAG terechtgekomen.
Voor de WOZ een zegen, maar voor de bijhouding een ramp: inderdaad zijn schuren die vele malen groter zijn nu niet in de BAG opgenomen (want, vergunningvrij en ook meestal zonder noemenswaardige fundering). Blijft ook iedere keer discussie bij BGT opbouw. Het is zo langzamerhand wel een rommeltje geworden.

**Comment by ToineC** [comment]
Enige verduidelijking zou toch nog wel op zijn plaats zijn m.b.t. de prefab schuurtjes. In het OHB (blz. 41) staat nu:
_“Geen pand: Een prefab houten schuur (zoals verkocht in bijvoorbeeld bouwmarkten en tuincentra) wordt niet als afzonderlijk pand afgebakend. Noot: Dit betreft de prefab schuren zoals verkocht in bijvoorbeeld bouwmarkten. Overige prefab gebouwen worden afzonderlijk getoetst aan de criteria voor pand.”_

Dit impliceert naar mijn mening dat de zelf getimmerde schuren (hoe klein ook…) op dit moment al wel als pand afgebakend dienen te worden. Overigens zijn er gemeenten die nu álle schuurtjes als pand afbakenen omdat aan de buitenkant meestal niet te zien is of het schuurtje uit de bouwmarkt komt. Er zijn ook gemeenten die een bepaalde oppervlakte hanteren om te bepalen of een object als pand aangemerkt dient te worden (bijv. > 10 m2). 

Het laten staan van de voorwaarde ‘vergunningplichtig’ in het nieuwe OHB zou deze discussie nog ingewikkelder maken omdat dan van elk bouwwerk onderzocht zou moeten worden of het (al dan niet) vergunning plichtig is. Eenzelfde object  zou dan de ene keer wel als pand aangemerkt worden en een andere keer weer niet. Ik zou willen pleiten voor eenduidigheid op basis van objectkenmerken.
