### ISSUE TITLE
Namen van objecttypen en attribuutsoorten

### ISSUE THREAD

**Issue by ArjanKloosterboer** [Geonovum/IMBAG#20]
In de Catalogus BAG hebben objecttypen en attribuutsoorten namen die in normaal Nederlands geschreven zijn, zoals 'Openbare ruimte' en 'Naam openbare ruimte'.  In het ImBAG zijn deze gewijzigd in technisch ogende namen zoals OpenbareRuimte en naamOpenbareRuimte. Het lijkt erop dat xml-tags in de Catalogus BAG nu tot namen zijn gepromoveerd.
Wat is hiervan de reden? Het is toch een semantisch conceptueel informatiemodel, toch geen op uitwisseling gericht technisch model? Welke toegevoegde waarde heeft dit?
Ik stel voor de naamgeving van de Catalogus BAG te behouden, tenzij er gegronde redenen zijn daarvan af te wijken. Dan moeten die wel vermeld worden. En daar ben ik dan heel benieuwd naar.

**Comment by rindertdijkstra** [comment]
Helemaal mee eens. Maak alsjeblieft onderscheid tussen het semantische model en de modellen die je gebruikt voor de implementatie. Iedere Nederlander moet het model kunnen lezen. Er is geen enkele reden om af te wijken van de naamgeving in de BAG.
Een uitwisselingsmodel is voor techneuten. Het begint altijd met een semantisch model in gewoon Nederlands.
