### ISSUE TITLE
Intrekken Woonplaats / Openbare Ruimte (OR) bij splitsing?

### ISSUE THREAD

**Issue by RalphStremme** [Geonovum/IMBAG#22]
Document: Hoofdstuk_Objectafbakening; blz 2

Samenvatting:
(Onnodig) veel berichtenverkeer

Beschrijving:
Waarom is het intrekken van een woonplaats (WPL) of openbare ruimte (OR) bij een kleine mutatie nodig. Indien een OR of een WPL wordt ingekort door bv een gedeeltelijke hernoeming of een grenscorrectie lijkt het voldoende om de betrokken nummeraanduidingen om te nummeren. 
Stel een OR met 600 nummers wordt gesplitst in een nieuwe OR met 2 nummer en een met 598. Gaan we de afnemers dan opzadelen met 1200 berichten?!

Oplossingsrichting:
Alleen de objecten die getroffen worden door een besluit hernoemen.

**Comment by ArjanKloosterboer** [comment]
Ik ondersteun dit, maar om een ietwat andere reden. Een object vervalt alleen als er sprake is van het vervallen van het object, niet als er kenmerken van dat object wijzigen. Als het stukje aarde waarop een object betrekking heeft, iets kleiner of groter wordt, dan vervalt dat object niet maar wijzigt de geometrie  van dat object. Zo doen we dat bijvoorbeeld bij een pand waar een stuk aangebouwd wordt. Waarom doen we dat anders bij woonplaatsen en openbare ruimten? Als de gemeente besluit dat een straat iets verder doorloopt of juist wat korter wordt, dan is en blijft het hetzelfde object. Alleen het kenmerk 'geometrie' wijzigt van waarde. 
Ik zie geen redenen om bij wijziging van geometrie met openbare ruimten en woonplaatsen anders om te gaan dan met panden. Iemand anders wel?
