### ISSUE TITLE
Waarom documenten in PDF?

### ISSUE THREAD

**Issue by pvgenuchten** [Geonovum/IMBAG#23]
Geweldig dat geonovum het github platform gebruikt om feedback op een kandidaat standaard te verwerken. Ik begrijp echter niet waarom u het formaat pdf gebruikt om de standaard te publiceren, text gebaseerde formaten als rtf, markdown hebben het voordeel dat mutaties op de documenten inzichtelijk via commits identificeerbaar gemaakt kunnen worden en tevens dat vanuit issues rechtstreeks naar bepaalde regelnummers in de documenten kan worden verwezen

**Comment by SiNNuT** [comment]
Plus 1 voor deze suggestie. Bij voorkeur Markdown. Ook makkelijk voor hergebruik bijvoorbeeld ten behoeve van intern gebruik met aanvulling van bepaalde plusgegevens.

**Comment by emacgillavry** [comment]
Sluit me hierbij aan! Tekst in Markdown maakt het stukken makkelijker

Op 22 nov. 2016 20:41 schreef "SiNNuT" notifications@github.com:
