### ISSUE TITLE
Meer adressen vanuit belang voor het maatschappelijk verkeer

### ISSUE THREAD

**Issue by ArjanKloosterboer** [Geonovum/IMBAG#27]
In par. 2.2 wordt vermeld dat "Het aanwezig zijn van een adres voor een adresseerbaar object, is van essentieel belang voor het in het maatschappelijk verkeer kunnen aanduiden van het betreffende object."  Vanuit maatschappelijk verkeer is er m.i. een belang om ook van andere objecten (dan de objecten waaraan de BAG nu een adres toekent) een adres te hebben. Bijvoorbeeld vanwege (publieke) veiligheid zoals een autosloperij zonder opstal en een NS-station in een buitenwijk zonder opstal. 
Het is m.i. nu het moment om er over na te denken om de BAG op dit punt uit te breiden.
Dat geldt m.i. ook voor nevenadressen. Hoe wordt ingespeeld op het belang vanuit het maatschappelijk verkeer dat een bedrijf in een bedrijfsverzamelgebouw een uniek adres heeft? Ook hierover dient m.i. nu nagedacht te worden.

**Comment by Dorrestijn** [comment]
Bij bedrijfsverzamelgebouwen moet er volgens mij wel sprake zijn van een zelfstandig object. In de afgelopen jaren is er veel energie in gestoken om onterechte adressen in te trekken. Het is ook goed uit te leggen aan de verhuurders. Het probleem is vaak niet het feit dat ze geen adres krijgen, maar dat ze een eenmaal ontvangen adres niet meer mogen gebruiken. Want als we dat weer toe gaan laten, kunnen we alle studentenkamers en dergelijke ook weer gaan nummeren.

**Comment by TimSchoonebeek** [comment]
In de toelichting bij de objectafbakening staat op pagina 2 juist dat stations altijd als vbo afgebakend dienen te worden, ook als ze niet afsluitbaar zijn.
