### ISSUE TITLE
Levenscyclus van panden en verblijfsobjecten

### ISSUE THREAD

**Issue by ArjanKloosterboer** [Geonovum/IMBAG#28]
De afgelopen jaren is al vaker discussie gevoerd over de beperkingen van de wijze waarop de levenscyclus in de Catalogus BAG is uitgewerkt. Ik zie daarvan in de tekst (par. 3.6) niets terug. Grofweg gaat dit over twee onderwerpen:
- de BAG is een registratie van formele gebeurtenissen, niet van de werkelijkheid zoals bekend bij de overheid (bijvoorbeeld: een pand waarvoor een nieuwbouwvergunning is verleend wordt aan de BAG toegevoegd terwijl dat pand er in de werkelijkheid nog niet is en wellicht zelfs nooit komt); 
- Verbouwingen waarvoor een vergunning verleend is, i.h.b. als daarbij de geometrie gaat wijzigen; het verschil tussen de feitelijke werkelijkheid en de nieuw vergunde toekomstige werkelijkheid is niet eenvoudig aan de BAG te ontlenen. Oorzaak is m.n. het ontbreken van hierop gerichte statussen. 

Op beide onderwerpen cq. de levenscyclus als geheel is m.i. nu het moment daarin verbetering te brengen.

**Comment by Dorrestijn** [comment]
Vergunningen voor interne verbouwingen leveren inderdaad problemen op. Soms wordt een kantoorpand (na verlening van de vergunning) nog enige tijd als kantoor gebruikt voordat de verbouwing tot bv. een woongebouw plaats gaat vinden. In zulke geval is een "start (ver)bouw" wenselijk. Dat is namelijk het moment om het oude vbo (kantoor) en de oude nummeraanduiding daarvan in te trekken.

**Comment by ToineC** [comment]
@Dorrestijn 
Ik zou hier eerder het moment van 'verbouw gereed' voor gebruiken; dat is namelijk het moment dat de  aanpassingen doorgevoerd worden in de WOZ administratie (begindatum nieuwe taxatie). Bij de start van een verbouwing is de oude situatie immers nog aanwezig. Dit sluit m.i. ook beter aan bij de werkwijze bij splitsingen en samenvoegingen.
