### ISSUE TITLE
Waarschijnlijke bouwjaar van het Pand

### ISSUE THREAD

**Issue by ArjanKloosterboer** [Geonovum/IMBAG#29]
Par. 4.7.1 vermeld: "Bij het initieel opvoeren van een Pand wordt door de gemeente een reële inschatting gemaakt van het waarschijnlijke bouwjaar van het Pand."
Semantisch is het waarschijnlijke (en toekomstige) bouwjaar iets anders dan het feitelijke (en gerealiseerde) bouwjaar van het pand. Van belang is m.i. telkens eenduidigheid te hebben welke van de twee het betreft. Dat is nu lastig, moet afgeleid worden van de status van het pand. Eenduidiger is het hiervoor twee separate bouwjaar-attributen te hanteren dan wel één attribuut bouwjaar en een tweede (indicatie-)attribuut dat aangeeft wat de semantische betekenis is van de waarde van 'bouwjaar'.

**Comment by ToineC** [comment]
@ArjanKloosterboer 
Je geeft (terecht) aan dat het bouwjaar in combinatie met de status deze informatie al wel biedt; ik vraag me af wat zo'n extra attribuut dan toe zou voegen voor het gebruik van de BAG (in praktische zin dus...).
