### ISSUE TITLE
Openfrontstallen

### ISSUE THREAD

**Issue by Dorrestijn** [Geonovum/IMBAG#3]
Document: Hoofdstuk __: Objectafbakening (pandafbakening, punt 5)

Samenvatting: 
 Pandafbakening toestaan voor openfrontstallen en dergelijk agrarisch vastgoed, waarbij weliswaar een wand ontbreekt, maar waarbij wel voorzieningen getroffen zijn dat het vee het pand niet kan verlaten.

Beschrijving: 
Het is niet logisch dat dergelijke (zie link) grote agrarische stallen en opstallen ontbreken, maar dat een klein afsluitbaar opslagschuurtje dat er mogelijk naast staat wel in de BAG staat.
http://www.hummelink.nl/projecten/agrarische-sector/didam-hoeveslag-openfront-stal/

Oplossingsrichting:
Toestaan dat agrarisch vastgoed waar een wand ontbreekt uit oogpunt van dierenwelzijn, maar waaruit het vee niet kan ontsnappen, opgenomen wordt in de BAG

**Comment by Dorrestijn** [comment]
Nog een aanvulling hierbij. Er zijn open wagenloodsen met daarin afgesloten ruimten (b.v. een garage voor de auto van de boer). Vaak zijn deze wagenloodsen gefundeerd en voor een groot deel met stenen opgetrokken. Volgens de tekst mag alleen het interne deel als pand afgebakend worden omdat dat omsloten is door wanden. Dat lijkt me niet wenselijk en lijkt het me logischer om zulke wagenloodsen compleet op te nemen in de BAG, ondanks het feit dat deze niet geheel afgesloten kan worden. Soms zijn schuifdeuren aanwezig, maar dat is enkel te controleren na betreden van het "pand".

**Comment by lodewijkjessen** [comment]
Wij (de opstellers) hebben enkele vragen aan de lezers, na een toelichting.

Vanaf het begin van de wetsevaluatie is besloten geen aanpassingen in de objectklassen door te voeren bij de voorliggende wijzigingen van wet- en regelgeving en de uitwerking daarvan. Bij de panddefinitie blijft dus onder meer centraal staan dat een pand ‘afsluitbaar’ moet zijn. In de nu voorgestelde beslisboom is deze term vervangen door ‘volledig door wanden omsloten’. De term is afkomstig uit NEN2580:2007 en is niet bedoeld als inhoudelijke wijziging maar als verduidelijking door aan te sluiten bij een bestaande en breed geaccepteerde norm.
De ‘open veldschuur’ is een voorbeeld van een bouwwerk dat nooit als pand is beschouwd, omdat die nu eenmaal aan één zijde open is en dus niet afsluitbaar (c.q. niet volledig door wanden omsloten). Dit soort bouwwerken wordt overigens wel in de BGT opgenomen.
In par 2.3.3. van het OHB staat nu:
_Net als alle objecten moeten garageboxen, schuren en stallen voldoen aan alle criteria om als pand
onderscheiden te worden. Een garagebox, schuur of stal met een open gedeelte aan een zijde (of een
muur die met een doek is dichtgemaakt) voldoet niet aan het criterium afsluitbaar en wordt in de BAG
niet als pand afgebakend. Een schuur of stal met op circa één meter hoogte openingen wordt wel als
afsluitbaar beschouwd en als pand afgebakend._
De eerste twee zinnen sluiten in ieder geval aan bij het voorgaande (afsluitbaar / volledig door wanden omsloten). De laatste zin is inderdaad aanleiding tot een nadere afweging. De eis van een ‘muurtje’ van één meter leidt in de praktijk alleen al tot vragen omdat dat ‘muurtje’ steeds lager lijkt te worden. Ook zien we veel stallen met aan twee of meer zijden dit soort openingen en het is uit de tekst niet duidelijk hoe die zouden moeten worden beoordeeld.

Vanuit de definitie geredeneerd lijkt de conclusie voor de hand te liggen dat een bouwwerk met dit soort openingen niet aan de panddefinitie voldoet. Dat leidt echter tot vervolgvragen, zoals:
• In de huidige omschrijving is de (garagebox, schuur en) stal met opening op circa één meter wel als pand opgenomen. Dit terugdraaien zal impact hebben op de bronhouders, waarbij een werkafspraak natuurlijk tot de mogelijkheden behoort.
• Wat zou dit voor de afnemers betekenen.

**Wij zouden dan ook graag van zowel bronhouders als afnemers vernemen:**
• Hoe bronhouders op dit moment met de afbakening van dit soort bouwwerken in de BAG omgaan, eventueel met voorbeelden)
• Welke mogelijkheden zij zien om tot een eenduidige afbakening te komen, binnen de gegevens uitgangspunten
• Wat de impact voor afnemers zou zijn als de definitie strikt zou worden toegepast en de deels open bouwwerken (op termijn, werkafspraak) uit de BAG zouden verdwijnen.

**Comment by sholdert** [comment]
Zit een deel van het antwoord misschien in de geometrie? Als bij deze objecten en deel wel is afgesloten en volledig door wanden omsloten en een deel niet (al dan niet met een muurtje of doek), kan er dan niet worden gekeken naar de dak constructie. Als deze constructie 1 geheel is en voor een Bag pand de geometrie van de het boven aanzicht moet worden geregistreerd… Is het dan niet mogelijk de geometrie van het gehele dak van het gehele pand te registreren en niet alleen van het afsluitbare deel.

**Comment by PieterBs** [comment]
Ik denk dat de uitzondering moet zitten in de agrarische objecten. Waarom zou je de panden niet registreren. Het gaat niet om panden van 5 vierkante meter, maar meer in de orde van panden met een oppervlakte van 100 tot wel 1500 vierkante meter.

Wij registreren de objecten nu als overige gebouwde objecten, maar deze objecten zijn zoals jullie weten niet authentiek en puur nu voor eigen registratie dat we weten dat er wat zit en wat er op de betreffende locatie zit.

**Comment by marleenhermans** [comment]
In Houten hebben we apart alle werktuigloodsen (zo worden veel van dit soort schuren genoemd in de WOZ) met obliekfoto's bekeken bij de opbouw. Van de daarna verleende vergunningen hebben we ook inderdaad veelal een klein deel van die loods apart afgebakend, omdat het zo op tekening staat.
Dat geeft nu heel veel discussies bij de verschilafhandeling BAG-BGT. En er blijkt dat in meerdere gevallen die loods opeens mogelijk te sluiten is omdat er overheaddeuren zijn geplaatst. Dat is WEL een BAG pand.

**Comment by Hilversum** [comment]
Een open stal of opslagloods gaan niet in de BAG mee. Deze komen in de BGT met een aanduiding. Als je alle open stallen en loodsen etc gaat opnemen, dan verwatert de eis tot afsluitbaarheid. Anderzijds kun je beslissen om het leeuwendeel van deze objecten wel op te nemen in de BAG. Dit doe je bijv. als afnemers hiertoe goede argumenten op tafel leggen.  Ik heb tot nu toe geen zwaarwegende reden gehoord om deze open objecten wel op nemen. Via de BGT geometrie zijn deze objecten wel bekend. Je mist alleen een pandid, een bouwjaar en wat statusgegevens.

**Comment by RalphStremme** [comment]
Richting mijn (interne) afnemers heb ik ook wel discussies over de grotere open opstallen. Daarbij is mijn mening dat welke norm gehanteerd moet worden pas volgt na het vaststellen van de informatiebehoefte. 

Is het mogelijk om meer te kijken naar de mate waarin in dergelijke panden verbleven kan worden (ook vee en materieel) dan naar de verschijningsvorm van de wanden?
Een open frontstal heeft zoals al aangehaald vaak een functionele barriere voor vee en bij materiaal loodsen is soms een ketting tussen de wanden al voldoende.

Er is in de keten sprake van informatiebehoefte. Het is raar om dergelijke panden niet uniform tussen de BAG, WOZ en BGT te benoemen.

Het werk hebben bronhouders dus toch al in het bijhouden van de gegevens in de WOZ en BGT registraties. Dit staat los van eventueel gebruik buiten de muren van de gemeente (vergeef me de woordspeling). Dit neemt niet weg dat een dergelijke aanpassing zeker een impact zal hebben op met name agrarische gemeenten. Hier zal zeker naar gekeken moeten worden, maar was dat een beletsel bij de verzorgingstehuizen en studentenhuisevesting?
