### ISSUE TITLE
Wat wordt er verstaan onder een semantisch gegevensmodel?

### ISSUE THREAD

**Issue by lennartvanbergen** [Geonovum/IMBAG#30]
Modellenbureau Kadaster houdt opzettelijk NEN3610 aspecten 'weg' uit semantische gegevensmodellen 

Wij modelleren een semantisch begrippenkader in een semantische catalogus, zie https://brk.basisregistraties.overheid.nl/

En als we die in een gegevensmodel modelleren, dan doen wij dat conform het metamodel voor informatiemodellen. Dat is heel bewust zonder NEN3610 aspecten en ook heel bewust zonder StUF aspecten c.q. bevat geen standaarden die _context specifiek_ worden toegepast. 

Dit noemen wij een semantisch gegevensmodel. Omdat deze context onafhankelijk is, en zuiver bij de semantiek blijft, kan dit model de basis vormen voor 'elk denkbaar' implementatie specifiek model, met behoud van semantiek. Denk aan NEN3610, StUF, specifieke koppelvlak services en specifieke producten.  

Als ik zo naar IMBAG kijk, dan valt direct op dat IMBAG als NEN3610 model is gepositioneerd. Dat lijkt, vanuit modellenbureau Kadaster, niet te passen bij onze interpretatie. Vandaar dat ik nieuwsgierig ben naar wat er onder een semantisch gegevensmodel wordt verstaan? In het bijzonder in relatie tot NEN3610.

Overigens helemaal goed om een NEN3610 model te maken. Kadaster maakt ook IMKAD als NEN3610 model. Maar dit kan ons inziens niet zonder eerst een implementatie onafhankelijk model te maken. Anders wordt er een belangrijk model, de belangrijkste als ik het zo mag zeggen, overgeslagen. Want als je dit model niet overslaat, dan is deze de basis van de model-driven stack, en houdt dus elke variant die je ervan afleidt met elkaar in lijn. Zo kan je er bijvoorbeeld een NEN3610 model EN een StUF model van maken, door specifieke eisen en regels voor uitwisseling in het GEO domein en het gemeentelijke domein toe te passen. Alsmede de koppeling met het semantische begrippenkader. 

Ik ben daarom blij dat IMBAG in het KKG metamodel gemodelleerd zal gaan worden. Echter, als ik naar het IMBAG model nu kijk, is dat nog niet gedaan. 

Dat is denk ik ook de opmerking. 
- Eerst een semantisch gegevensmodel conform KKG: IMBAG KKG
- Dan NEN3610 toepassen om er een NEN3610 sectormodel van te maken: IMBAG NEN3610
- Aan KING vragen om, op basis van het model conform KKG, er een RGB en StUF van te maken

IMBAG NEN3610 en 'IMBAG'-StUF staan dan naast elkaar, traceerbaar vanuit de bovenliggende semantische ('sectoraal onafhankelijke') modellen.

- IMBAG als semantisch begrippenkader opnemen in de catalogus hiervoor (die ingericht wordt voor KKG )

Resultaat: het semantische begrippenkader, IMBAG KKG, IMBAG NEN3610 en IMBAG-RGB en  IMBAG StUF zijn consistent met elkaar, in een model-driven stack, traceerbaar. 

De LV BAG kan dan haar implementatie dan ook baseren op IMBAG KKG. En dus IMBAG StUF ontvangen van gemeentes en IMBAG NEN3610 uitleveren aan afnemers. 

En zo wordt het allemaal mooi en in samenhang :-)

**Comment by ArjanKloosterboer** [comment]
Mooi betoog. Maakt duidelijk dat er een onderscheid is tussen een conceptueel/semantisch model en een op uitwisseling gericht model. Oftewel, het bekende onderscheid tussen het WAT en het HOE. Laten we dat er vooral inhouden. Die twee invalshoeken vermengen geeft verwarring en onduidelijkheid. 
Zie ook discussie https://github.com/Geonovum/IMBAG/issues/15.
