### ISSUE TITLE
Verschillen in beeld (?) 

### ISSUE THREAD

**Issue by lennartvanbergen** [Geonovum/IMBAG#31]
Ik begrijp dat dit het platform is om reacties te geven op IMBAG 2.0

Deze reactie gaat over waar de verschillen zitten t.a.v. IMBAG zoals geïmplementeerd in de LV en zoals geïmplementeerd in RSGB en StUF. Zijn deze in beeld? Ik kan nl geen lijst met verschillen vinden. 

Deze verschillen in beeld brengen is erg belangrijk, omdat bronhouders, de LV (en Afnemers) dezelfde conversies moeten doorvoeren. Als dat nl niet consistent overal op dezelfde manier gebeurd, dan loopt de LV scheef t.a.v. de bronhouders (en Afnemers). Daarom moeten de beoogde functionele verbeteringen en alle andere verschillen in IMBAG KKG doorgevoerd worden, in IMBAG NEN3610 , in IMBAG StUF, in elke implementatie daarvan en consistent met elkaar. En helder in beeld t.a.v. de verschillende versies van StUF en IMBAG die in gebruik zijn bij bronhouders en de LV. Dat zou de LV aan ICT kant ook zeker helpen t.a.v. de impact van de benodigde conversies. Immers, de LV zal de bestaande services ook nog een tijdje moeten blijven ondersteunen. Dit is de achtergrond van deze reactie. Dit zal bekend zijn. 

Dit moet in beeld zijn voordat IMBAG 2.0 wordt vastgesteld, om te voorkomen dat impact in de keten onnodig groot wordt. Ik weet ook dat het IMBAG 2.0 traject hier zeker over nadenkt en ditzelfde zegt.  

Er kan dan uitgelegd worden _wat_ het verschil is, omdat implementaties bij de LV, bronhouders en afnemers moeten kunnen beoordelen hoe ze hiermee om moeten/willen gaan (afgezien van de 'waarom vraag'). 

Echter, waar zijn de verschillen lijstjes? 

--

Er is ook aanleiding om te denken dat er verschillen zijn, waarvan een aantal vermoedelijk niet bedoeld en/of niet gewenst vanuit het IMBAG 2.0 traject. Hieronder een aantal hiervan:

- IMBAG heeft in de loop van de jaren een aantal wijzigingen doorgemaakt. Dit heeft geresulteerd in een laatste versie, IMBAG 1.0 (beta), zoals gebruikt voor de services bag-bevragen 2.0. Zie: http://www.kadaster.nl/-/bag-bevragen . De IMBAG die ik zie in de EAP is niet gebaseerd op de meest actuele IMBAG. Anders gezegd, een (aardig) aantal (kleine) wijzigingen zijn 'teruggedraaid'. Het lijkt, ook om de impact bij Afnemers en bij de LV te beperken, handig om IMBAG 2.0 te baseren op het meest actuele IMBAG die de LV nu biedt.  

Aanvullend zijn een aantal attributen naar BAG Object zijn verhuisd, en zijn definities zijn veranderd. Bijvoorbeeld: 
- identificatie. Er zit nog maar 1 identificatie in het nieuwe model, in BAG Object. Het type daarvan is veranderd. Van objectnummer (conform catalogus) naar NEN3610ID. Terwijl er semantisch niets is veranderd. Dat veroorzaakt dus veel impact, met weinig toegevoegde waarde. Ook is het type van woonplaats in de BAG anders dan van andere BAG objecten. Toch zit er maar 1 definitie van identificatie in het model. Aanvullend is het patroon van deze identificaties per BAG object anders. Dit lijkt een stap te ver te zijn gegaan qua modellering. Als je hier XSD's van probeert te genereren, dan kan dit niet goed gaan. Immers, 1 definitie in UML = 1 definitie in XSD. Je kan niet uit 1 definitie in UML meerdere definities in XSD genereren.

- begindatum geldigheid. Deze is anders genoemd. Dit terwijl NEN3610 niet de attribuutnaam voorschrijft. Lijkt daarom een onnodige verandering, maar wellicht is er een belangrijke reden. Aanvullend in dit geval is het zo dat het type is veranderd van datumtijd, naar datum. En dat is semantisch gezien geheel correct. Heel goed. Dat kunnen we ook converteren in de LV. Echter, waar laten we het 'tijd' deel? Want datum begin geldigheid is onderdeel van de unieke sleutel van BAG voorkomens van BAG objecten. Dus die moet in de conversie wel een plekje krijgen. Die zit ik echter niet terug. Dus dat valt niet te converteren. Dat is nogal vervelend voor een attribuut die onderdeel uitmaakt van de unieke sleutel. Apart is ook dat het BAG Object heet, terwijl het gegeven over datum begin geldigheid over BAG voorkomens gaat. Deze geldt niet voor een object als geheel, wat wel zo is bij identificatie, dat is een echt objectattribuut, maar juist die kan niet in BAG Object, omdat de identificatie niet gelijk is voor de verschillende BAG objecten. Hier lijkt dus nog iets te missen in IMBAG 2.0 wat problematisch is voor conversie. 

- patronen waaraan de data moet voldoen. Denk aan bouwjaar pand. In de huidige catalogus moet die lengte 4 zijn. Bouwjaar 999 pas hier bv alleen in als 0999. Er zijn meer van dit soort kleine dingetjes die in de loop der jaren aangescherpt zijn.

- inOnderzoek. Deze is qua definitie veranderd van een indicatie Ja/Nee 0..1 , naar een String, 0..*. Maar precies deze is qua naamgeving wel gelijk gebleven. Dat valt dus lastig te converteren in de LV. Een van de twee moet immers een andere naam krijgen. 

Er zijn dus een flink aantal kleine wijzigingen doorgevoerd. Een aantal zijn functioneel, een aantal zijn vanuit NEN3610 (en een aantal zijn vermoedelijk onbedoeld vanwege het niet verder werken op het meest actuele model). 

Ik wil er daarom voor pleiten om de verschillen in beeld te brengen t.a.v. het meest recente IMBAG model in de LV, voordat IMBAG 2.0 vastgesteld wordt . Dan is voor wat betreft de LV in ieder geval heel helder wat de verschillen zijn. 

En ook welke daadwerkelijk noodzakelijk zijn om de beoogde/gewenste functionele verbeteringen vanuit het IMBAG 2.0 traject door te voeren. Alle andere verschillen zijn dan ook direct helder qua positionering, te weten omdat deze gewenst zijn vanuit de NEN3610 insteek (of onbedoeld, maar ik ga er even vanuit onbedoelde verschillen op tijd weggepoetst zijn/worden, voor vaststelling van IMBAG 2.0 dus).

**Comment by Debatse** [comment]
In aanvulling op het voorgaande is de authenticiteit van een aantal attributen aangepast. Ik weet niet of dit het gevolg is van een wetswijziging.  Ik kan nergens achterhalen of dat ook daadwerkelijk het geval is of per ongeluk is gebeurd.

**Comment by Debatse** [comment]
Wij hebben al eerder verzocht om de verschillen in beeld te brengen maar daar is bij de review van de gegevenscatalogus helaas niets meegedaan.
