### ISSUE TITLE
inOnderzoek attributen voor onderlinge relaties BAG-objecten niet volledig

### ISSUE THREAD

**Issue by HansvanderMeij** [Geonovum/IMBAG#33]
Document:
Catalogus BAG 0.4, pag. 21

Beschrijving:
In de tabel staan de mogelijke attributen vermeld die 'in onderzoek' kunnen worden gezet. Daarbij zijn een aantal onderlinge relatieattributen opgenomen (bijv. pandrelatering bij verblijfsobject), maar lang niet allemaal.  De ontbrekende zijn:

Nummeraanduiding: bijbehorende openbare ruimte en bijbehorende woonplaats
Verblijfsobject: aanduiding hoofdadres en (eventueel) aanduiding(en) nevenadres
Standplaats: aanduiding hoofdadres en  (eventueel) aanduiding(en) nevenadres
Ligplaats:  aanduiding hoofdadres en  (eventueel) aanduiding(en) nevenadres

Oplossingsrichting:
Bovengenoemde ontbrekende relatieattributen ook voorzien van de mogelijkheid om 'in onderzoek' te plaatsen.

**Comment by TimSchoonebeek** [comment]
Ik vraag me af of dit in de praktijk wel iets toevoegt: Hoe kun je nu aangeven dat nummer 5 niet aan de A-straat maar aan de B-straat hoort? Wie zal in de gaten hebben dat je de verkeerde openbare ruimte hebt geselecteerd i.p.v. dat men denkt dat het huisnummer in de andere straat ontbreekt?

Voor de aanduiding hoofd- of nevenadres denk ik eerder dat je dat op het niveau van de nra zou moeten kunnen aangeven. Dan hoeft dat ook maar op één objecttype aangepast te worden en niet de drie adresseerbare objecten. Tenzij ik de bedoeling van je opmerking verkeerd begrijp.

**Comment by HansvanderMeij** [comment]
@TimSchoonebeek - Het gaat mij enerzijds om consistentie van de nieuwe mogelijkheden om BAG-gegevens 'in onderzoek' te zetten.  Waarom is dit wel mogelijk bij andere relatieattributen en niet bij deze?

Het feit dat een nummeraanduiding aan een verkeerde openbare ruimte (en mogelijk ook woonplaats) is gerelateerd doet zich regelmatig voor op de grens van woonplaatsen en/of gemeenten, daar waar de ontsluitende openbare ruimte fysiek in een ander woonplaats (en/of gemeente) ligt. 
In veel gevallen is er dan een (onjuiste) extra openbare ruimte opgevoerd die ook binnen dezelfde woonplaats wordt gerelateerd. Geeft ook een meer wenselijk adressering, alleen is dit BAG-technisch niet juist.
 
Dat blijkt meestal pas als je  dit in de BGT probeert te vertalen naar geometrie (hetzij via verplichte OpenbareRuimteLabel, hetzij via een optioneel RegistratiefGebied Openbare Ruimte).

Het feit dat de relatie naar nummeraanduidingen bij de drie adresseerbare objecttypen staat vermeld volgt automatisch uit de BAG-datamodel . . .  Je kan bij de Nummeraanduiding zelf geen relatie aangeven (of vinden) naar een adresseerbaar object, tenzij IMBAG dit gaat wijzigen, maar dat lijkt me niet wenselijk.

**Comment by TimSchoonebeek** [comment]
@HansvanderMeij Zo had ik het niet bekeken, maar wat betreft je voorbeeld is dan toch de openbare ruimte zelf fout (want gelegen in een andere gemeente en mag eigenlijk niet bestaan) en niet zozeer de relatie van het adres ermee?

Maar ik snap je punt, als dat elders ook kan, waarom op dit objecttype niet?

**Comment by HansvanderMeij** [comment]
@TimSchoonebeek Er is inderdaad eigenlijk sprake van een 'foute' Openbareruimte, maar niet het object dat in een andere woonplaats of gemeente is gelegen. Nee, het gaat dan om een soort 'dummy openbare ruimte' die dan maar met dezelfde naam in dezelfde woonplaats als het verblijfsobject wordt gepositioneerd . . Bij situaties op gemeentegrenzen is dit ook nog een overblijfsel van de opbouwtijd, waarbij men voorlopig kon volstaan met zo'n 'eigen' Openbare ruimte, omdat die van de buurgemeente nog niet beschikbaar was.
Het gaat dus om situaties dat het pand/verblijfsobject in de ene woonplaats/gemeente ligt en de ontsluitende openbare ruimte in de andere.  Dit kan het (ongewenste) effect geven dat je in het adres de woonplaats krijgt die bij de openbare ruimte hoort . . 
In mijn Haagse (opbouw)tijd hadden we daar prominente voorbeelden van, zoals het hoofdkwartier van de ANWB, dat fysiek in Wassenaar ligt, maar ontsloten wordt door de Wassenaarse weg die in Den Haag ligt . .   Was veel over te doen destijds en ook wel begrijpelijk.  
Want wat is nu leidend in het adres, de ligging van het object of de ontsluiting daarvan?  Voor beide is wat te zeggen, maar formeel geeft de ligging de doorslag en zijn 'dummy openbare ruimten' ook niet meer noodzakelijk of gewenst.  
Zeker niet nu er via de BGT toch ook iets van geometrie van een openbare ruimte duidelijk begint te worden (ook al is een puntvormig tekstelement als OpenbareRuimtelabel nog wel een hele globale geometrie ;-).
