### ISSUE TITLE
Advies BAG 2.0

### ISSUE THREAD

**Issue by ghost** [Geonovum/IMBAG#38]
De gemeente Amsterdam wil een advies uitbrengen voor de wijzigingen in de catalogus BAG 2.0:
team BAG Amsterdam:

 •namespace:     EENS met de aanpassing
 •toevoeging time datum LV: geen mening
 •'in onderzoek':  EENS met de aanpassing

**Comment by ArjanKloosterboer** [comment]
Ik zou graag hier lezen wat de overwegingen zijn van Amsterdam om in te stemmen met deze wijzigingen, met name die van namespace, en of de consequenties daarvan (voor BAG- en andere applicaties en de uitwisseling van BAG-gegevens) zijn overzien en meegewogen. Zie ook discussie #10

**Comment by ghost** [comment]
Op verzoek de uitleg met de namespace-uitbreiding:
Het grote voordeel is dat je kunt gaan koppelen met andere registraties zonder dat er kans is op een dubbel ID. In de producten die ontstaan uit de BAG voor afnemers hoeft deze namespace niet meegenomen te worden. (wordt wegggefilterd).

**Comment by ArjanKloosterboer** [comment]
Van dat koppelen, die snap ik niet. Als je bijvoorbeeld een BAG-object wil koppelen aan een WOZ-object, dan moet je specifiek weten welk object van welk type je wilt koppelen. Je weet dan of je met een Pand of Verblijfsobject te maken hebt. Dan volstaat de BAG-id. 
Interessant is dat je schrijft dat die namespace in producten voor afnemers niet meegenomen hoeft te worden. Het lijkt dan meer iets voor een op uitwisseling gericht informatiemodel (voor een andere doelgroep dan afnemers; voorbeelden?) dan voor een semantisch/conceptueel model. Zie ook discussie #30
