### ISSUE TITLE
Moment van mutatie bij splitsing

### ISSUE THREAD

**Issue by rphvanderheijden** [Geonovum/IMBAG#39]
Document: 20161010_BAG_gegevenscatalogus_concept_v0.4.pdf, paragraaf 3.6 blz. 12
Samenvatting:
Mutatie status geschied op een foutief moment. 
Beschrijving:
Citaat: “Bij de start van de verbouw worden deze ‘oude’ verblijfsobjecten ingetrokken, terwijl de nieuwe zodra zij gebruiksgereed zijn de status ‘in gebruik (niet ingemeten) verkrijgen.”
Op het moment “start bouw” wordt in de BAG alleen gemuteerd bij nieuwbouw en niet bij verbouw. Bij de start van de verbouw kunnen de nieuwe verblijfsobjecten niet de status “in gebruik…” hebben.
Oplossingsrichting:
Tekst zou moeten zijn: “Bij de gereedmelding van de verbouw worden deze ‘oude’ verblijfsobjecten ingetrokken, terwijl de nieuwe de status ‘in gebruik (niet ingemeten) verkrijgen.”

**Comment by TimSchoonebeek** [comment]
Mee eens, mede om een andere, meer praktische reden: Er kunnen namelijk nog inschrijvingen actief zijn in de BRP. Niet iedere verbouwing is per se zo rigoureus dat je er niet zou kunnen wonen op dat moment. Daarnaast als je de start verbouw al zou weten, is het niet handig om 3 keer te muteren: verlening (ontstaan nieuwe objecten), start (intrekken oud object) en gereedmelding (statuswijziging nieuwe objecten). Ik ken geen voorbeelden van gemeentes die de start van de verbouw actief controleren. In de praktijk komt het dan toch op het gelijktijdig afvoeren van het oude object met de gereedmelding van de nieuwe objecten.

**Comment by HansvanderMeij** [comment]
Mee eens omdat dit inderdaad een ongewenst vacuüm voor afnemers (zoals de BRP) kan voorkomen.  Daarbij zou dit ook direct kunnen leiden tot de status 'in gebruik' als direct ook de consequenties qua oppervlakte  van de nieuwe verblijfsobjecten duidelijk zijn.  Als die alsnog bepaald moeten worden (bijvoorbeeld via een bezoek van een bouwinspecteur) is voorlopige de status 'in gebruik (niet ingemeten)' logischer.
Overigens is deze passage niet voor iedere verbouwing bedoelt, maar met name voor splitsing of samenvoeging (dus verandering van het aantal verblijfsobjecten).
