### ISSUE TITLE
Andere vormen van twee-over-een-trapwoningen

### ISSUE THREAD

**Issue by Dorrestijn** [Geonovum/IMBAG#4]
Document: Hoofdstuk __: Objectafbakening (afbakening verblijfsobjecten, punt 3)

Samenvatting: 
Aangeven of de definitie twee-over-een-trapwoningen ook toegepast kan worden op andere situaties.

Beschrijving: 
In de beschrijving staat dat de twee-over-een-trapwoning in oude kernen soms voorkomt. Deze situatie kan zich echter ook voordoen bij zelfstandige bovenwoningen. Zijn deze twee-over-een-trapwoningen een uitzondering voor een specifiek aangeduide situatie in een bepaalde stad of kan de definitie ook toegepast worden in elk willekeurig pand in elke gemeente.

Oplossingsrichting:
Duidelijker aangeven wanneer in soortgelijke situaties wel of niet overgegaan moet worden tot objectafbakening

**Comment by lodewijkjessen** [comment]
Reactie en vraag van de opstellers:

De huidige tekst over de twee-over-een-trapwoningen staat er vrijwel vanaf het begin, met name vanwege oudere bebouwing. Sindsdien is deze tekst niet meer inhoudelijk besproken. Belangrijke uitgangspunten bij de afbakening zijn de uniformiteit en de objectgerichtheid; alleen in bijzondere gevallen kan daarvan worden afgeweken.

**We zouden graag voorbeelden ontvangen** van meer recente bouwwerken waarin mogelijk een vergelijkbare situatie aan de orde is om ons een beeld te kunnen vormen.

**Comment by Hilversum** [comment]
De twee-over-een-trap-woning is een eenvoudige versie van de 'gemankeerde ontsluiting' van een verblijfsobject met functie woning.  Ik wijs bijv. naar de 'toevoeging bij het Objectenhandboek over de studentenflats'. Dit soort situaties; daar hebben wij meerdere van. Dit noemt men in de Toezichtswereld: de 'onvrije woning'. Dit zijn woningen met een complete set aan voorziening, maar een deel van de voorzieningen bevinden zich op 'gang' of zijn via de gedeelde verkeersruimte ontsloten.  In dit verband is ook nog de bijgevoegde uitspraak van een rechtbank relevant in het kader van de WOZ (zie het ander Issue: Verschil BAG-WOZ t.a.v. toilet in gedeelde verkeersruimte). Ook ontsluiting via een cafë of winkel zijn voorbeelden van gemankeerde ontsluiting. Ik zou de twee-over-een-trap-woning niet zien als een categorie, maar als een van de vormen van een : "gemankeerde ontsluiting".  Toegang via een winkel is een veel voorkomende vorm in de binnensteden. Juist in binnensteden waar wonen-boven-winkel wordt gepromoot is het ongewenst om (complete) woningen weg te moeten laten uit de BAG, omdat er alleen wat aan de ontsluiting mankeert....Voor de WOZ tellen deze objecten wel mee. Ook voor BRP is het efficienter en het is duidelijk naar de burger als we alle zelfstandige woningen met een eigen adres opnemen in de BAG. Het gaat er om; hou het grijze gebied tussen zelfstandige woningen en kamerbewoning zo klein mogelijk.

**Comment by PieterBs** [comment]
Dit geldt niet alleen voor wonen boven winkels, maar ook voor woningen boven horecagelegenheden, waarbij de ontsluiting naar de woning plaatsvindt via de algemene gebruiksruimte van de horecagelegenheid. Vervolgens kunnen zich naast de het vbo van de horeca, nog een vijftal woningen bevinden die niet worden geregistreerd in de BAG, maar als 1 vbo worden opgenomen in de BAG.

**Comment by Hilversum** [comment]
De BAG dient een doel. Uniformering van registraties...Woningen weglaten omdat er aan de ontsluiting/opgang iets mankeert, is het paard achter de wagen spannen. In veel gevallen is van binnen naar buiten geredeneerd er een woning voor de BAG, maar omdat de ontsluiting rommelig is, laten we dan deze zelfstandige woning(en) weg? Wat mij betreft; echt niet.  De belangrijkste kenmerken zijn een afsluitbare en zelfstandige eenheid van gebruik. Dat ik door een cafe of een winkel of een hal van een andere woning ga, dat is een rommelige ontsluiting, maar het is bijzaak t.o.v. het bestaan van de woning...

**Comment by PieterBs** [comment]
Ben ik het deels met je over eens. Maar woningen boven winkels, waarbij je via de trap via de winkel de woning benaderd registreer je ook niet in de BAG als een apart verblijfsobject, waarom dan wel die woning die je op dezelfde manier benaderd in de situatie van de horecagelegenheid (hierboven geschetst)?

**Comment by SiNNuT** [comment]
@Hilversum Als je echt door een café of winkel moet om de woning te bereiken dan is er m.i. toch echt geen sprake meer van een gedeelde verkeersruimte of iets wat kenmerken van een gedeelde verkeersruimte vertoont en dus ook geen apart VBO voor de woning. In een dergelijk geval is mij ook geen bestaande uitzonderingsregel bekend en het staat ook niet in de nieuwe documenten.

Onder andere door de beantwoording van diverse klantvragen door het Kadaster (vervolgens weer gedeeld op LinkedIn e.d.) is het begrip gedeelde verkeersruimte echter de laatste jaren wel vrij ruim geïnterpreteerd. Zodra er sprake was van iets dat leek op een gang, een trapportaal of een hal in een VBO waarlangs een ander object werd ontsloten mocht je overgaan tot afbakening van een apart VBO. De praktijk leert dat gemeentes daar verschillend mee omgaan. Het zou mooi zijn dat de nieuwe teksten hier expliciet duidelijkheid in verschaffen.

**Comment by PieterBs** [comment]
@SiNNuT
Er wordt wel steeds gesproken over dat een gedeelde verkeersruimte moet voldoen aan iets wat lijkt op een gang, een trapportaal of een hal. Maar expliciet uitgeschreven kan ik dit zo niet terugvinden. Enig duidelijkheid hierover is wel van toepassing met name door de twee-over-één-trap objecten.

In het document: "Toelichting concepttekst objectafbakening BAG" wordt wel gesproken over de ruime interpretatie van de 'gedeelde verkeersruimte'. Daarbij komt er weer een ruime interpretatie bij dat men spreekt over 'maatschappelijk belangenafweging'. Hoe gaan de bronhouders dit interpreteren. Ik zie liever eenduidigheid over het wel en niet afbakenen van objecten.

De toelichting zegt het volgende:
Wel is op basis van een maatschappelijke belangenafweging in aantal specifieke situaties toegestaan dat een VBO tevens dient ter ontsluiting van een ander VBO. In alle andere situaties dient een VBO te allen tijde te beschikken over een eigen toegang vanaf de openbare weg, gedeeld erf of een gedeelde verkeersruimte.

**Comment by SiNNuT** [comment]
@PieterBs Zoals ik aangaf, dit is nergens expliciet in de formele of ondersteunende teksten uitgeschreven maar een lijn die is te destilleren uit meerdere antwoorden vanuit het Kadaster over dit onderwerp. Ik weet niet of je de BAG bronhouders groep op LinkedIn  volgt maar zie bijvoorbeeld https://www.linkedin.com/groups/1960281/1960281-5925551046024798212 . Een ander voorbeeld met antwoord van Kadaster uit mijn gemeente kan ik je evt. mailen.

Net als jij zie ik ook graag eenduidigheid in het wel en niet afbakenen van objecten. Daarom ook mijn oproep dit zeer helder in de nieuwe catalogus (hoofdstuk objectafbakening) te omschrijven.

**Comment by PieterBs** [comment]
@SiNNuT
Wel grappig dat je dat aanhaalt, in de reacties heb ik namelijk ook zelf gereageerd, waarop een reactie is gegeven met een antwoord welke ik als vraag aan het Kadaster heb gesteld over het voorbeeld restaurant. Het antwoord wat ik terug heb ontvangen trek ik nu namelijk met alle reacties en het nieuwe handboek in twijfel.. Men heeft het nu over maatschappelijk belang, afsluitbaarheid als sloten deuren etc is niet van toepassing zolang bouwkundig constructief er niets aangepast hoeft te worden voor het plaatsen van een deur of soortgelijk iets.

En moeten we de gedeelde verkeersruimte nu letterlijk interpreteren of wat ruimer zien en dus de ruimte die men doorkruist om van de ingang van het restaurant naar de bovenwoning te komen zien als een gedeelde verkeersruimte?

**Comment by Hilversum** [comment]
Martijn Klomp zegt in de bovengenoemde linked-in discussie: Een gedeelde verkeersruimte maakt in beginsel echter geen onderdeel uit van een ander verblijfsobject.  Dat lijkt mij een goed begin. Daarnaast mag de bronbeheerder in uitzonderingsgevallen; objecten opnemen waarbij sprake  is van een gemankeerde ontsluiting. Hiermee doel ik op toegang via een winkel, een horecagelegenheid etc....In het kader van een maatschappelijk belang nemen we deze als verblijfsobject op. Gisteren ontdekte ik nog een maisonette die alleen ontsloten was via een deur, via de winkel. De maisonette had niets met de winkel van doen. Er stonden op dit moment geen mensen op ingeschreven, maar waren die er wel geweest, dan heb je nog een probleem erbij als je het adres niet opneemt in de BAG. Overigens wil de WOZ dit object ook apart afgebakend hebben. Het maatschappelijk belang verdraagt zich niet met een rigide hantering van het begrip ontsluiting. Wat zouden de brandweer of de politie willen weten over het pand, waar op de begane grond een winkel is en boven een woning....Tja. Het is een gevalletje van oei, ach en wee voor de 'preciezen' onder ons, maar weglaten is niet realistisch. Zeker als er achter de binnendeur een volledig zelfstandige woning zit. Het CBS wil deze ook wel meegeteld hebben en zo kan ik nog wel meer afnemers noemen. Wat mij betreft zijn er genoeg redenen om deze vbo's met gemankeerde ontsluitingen op te nemen in de BAG en daarop het Objectenhandboek aan te passen...
