### ISSUE TITLE
Wel of niet opvoeren van een nieuwe identificatie bij wijziging geometrie openbare ruimte?

### ISSUE THREAD

**Issue by rphvanderheijden** [Geonovum/IMBAG#41]
Document: 20161010_BAG_gegevenscatalogus_concept_v0.4.pdf, paragraaf 3.7.2 blz. 14
Samenvatting:
Een stelling die afwijkt van het antwoord van het Kadaster op een door de Gemeente Breda gestelde vraag. 

Beschrijving:
Citaat: “Als de geometrie van een Openbare Ruimte of Woonplaats wijzigt, wordt altijd een nieuw object met een nieuwe identificatie opgevoerd.”

Op 21-10-2016 stelde het Kadaster dat de werkgroep woonplaatsgrenswijzigingen geadviseerd heeft het aanmaken van nieuwe id's te beperken en dit alleen te doen bij splitsingen waarbij de afgesplitste delen geen onderdeel uitmaken van een bestaande woonplaats. De werkgroep heeft geadviseerd deze werkwijze ook toe te passen bij openbare ruimten.

Oplossingsrichting:
Afstemmen welke werkwijze gehanteerd dient te worden.

**Comment by ArjanKloosterboer** [comment]
Zie ook discussie https://github.com/Geonovum/IMBAG/issues/22. Lijkt over hetzelfde te gaan.
