### ISSUE TITLE
Nutsvoorzieningen: verticale deur onder maaiveldniveau = pand, horizontaal luik = geen pand?

### ISSUE THREAD

**Issue by TimSchoonebeek** [Geonovum/IMBAG#43]
Toelichting objectafbakening, p2 onder inhoudelijke aanpassingen:
- Ondergrondse nutsvoorzieningen: hierbij wordt geen toegangsdeur boven het maaiveld meer vereist.
Objectafbakening, p8 6. Is het bouwwerk betreedbaar?
Een pand dient bij de totstandkoming te beschikken over een of meerdere verticale toegangsdeuren [...] Een bouwwerk dat uitsluitend beschikt over andersoortige toegangen, zoals een horizontaal toegangsluik [...]

Concludeer ik hier dan juist dat voor de ondergrondse nutsvoorzieningen geldt dat ze alleen als pand opgenomen worden als ze een verticale toegangsdeur hebben, ongeacht of de deur zich boven of onder het maaiveld bevindt?

**Comment by HansvanderMeij** [comment]
Dit lijkt me een juiste conclusie en eigenlijk was dit al zo ten tijde van de opbouw/oplevering van de BAG.  Althans, ik kan me dit niet anders herinneren.

Tegelijkertijd is 'boven maaiveld' met de BGT-benadering een relatief begrip geworden.  Als er een trap naar 'beneden' loopt naar een toegangsdeur die zich 2 meter of meer lager bevindt, dan is die trap ook nog steeds 'maaiveld' of beter gezegd in BGT-termen 'relatieve hoogteligging 0'.
