### ISSUE TITLE
De uitzondering voor zorgcomplexen wordt de norm? (Mogelijkheid voor het plaatsen van de voorzieningen i.p.v. daadwerkelijk aanwezig)

### ISSUE THREAD

**Issue by TimSchoonebeek** [Geonovum/IMBAG#44]
Op pagina 13 van de nieuwe Objectafbakening lees ik in de basisvoorzieningen dat de aansluiting voldoende is en dat het er niet per se hoeft te zijn.

Dit gold tot nu toe juist als uitzondering voor de zorgcomplexen. Nu lees ik dat dit voor o.a. de woonfunctie gaat gelden en dus voor alle woningen. Als het er niet per se hoeft te staan, maar de aansluiting voldoende is verruimt dat m.i. het aantal objecten dat als zelfstandig moet worden gezien. Dit maakt het voor handhaving nog lastiger als een zelfstandig object niet is toegestaan. Tot nu toe is het verwijderen van de kookvoorziening of het toilet bv. voldoende om het weer onzelfstandig te maken. 

Hier krijg je een vervelende spagaat, waar volgens mij niemand mee geholpen is. Aan de ene kant moet je een verblijfsobject constateren omdat het voldoet aan alle eisen, terwijl het niet gelegaliseerd mag worden. Dan is het bijna onmogelijk om de indicatie "geconstateerd" nog op te lossen. Want het weghalen van de voorziening is dan niet meer voldoende om het onzelfstandig te maken, de gehele aansluitmogelijkheid moet er dan uit gesloopt worden.

Ik begrijp ook wel dat in een nieuwbouwwoning de keuken er nog niet per se staat, als deze opgeleverd wordt. Maar het is wel bijna 100% zeker dat die er geplaatst wordt. Geen probleem voor de afbakening als zelfstandig object. Voor een afsluitbare studenten- of een illegaal verbouwde woning met aansluitingen naar mijn idee wel.

**Comment by HansvanderMeij** [comment]
Tja, een lastige.  Misschien is de parallel te trekken met een bouwwerk dat illegaal is gebouwd en na handhaving moet worden afgebroken.  Wanneer is dit voltooid? Als het er niet meer zichtbaar staat of pas als ook de fundering en alle leidingen zijn verwijderd?  
Een zichtbare verwijdering van de voorziening zelf zou dan toch moeten kunnen volstaan en wellicht ook het verwijderen van het zichtbare deel van de leidingen (al dan niet met een adequate afsluiter).  Zou toch moeten kunnen zonder echte sloop- en breekacties.
