### ISSUE TITLE
Die vermaledijde sloopvergunning staat er nog steeds in

### ISSUE THREAD

**Issue by JeroenRijkse** [Geonovum/IMBAG#48]
Betreft de BAG_gegevenscatalogus_concept_v0.4.pdf
In paragraaf 3.6 Levenscyclus op de pagina's 10, 11 en 12
Bij de levenscyclus van een pand komt wordt de term sloopvergunning verleend gebruikt.
Een sloopvergunning wordt vrijwel nooit meer verleend. Een vergunning is alleen nog van toepassing als het bestemmingsplan zich tegen de sloop verzet of als er sprake is van een vorm van monumentale waarde. In alle andere gevallen is er slechts sprake van een sloopmelding.
De term sloopvergunning in ieder geval niet meer gebruiken.
Het proces slopen moet aansluiten bij de huidige wetgeving voor het slopen van een pand.
Het zou beter zijn om aan te sluiten bij de huidige omgevingsvergunning gebruikte terminologie. Daar is o.a. sprake van deelprocessen: bouwen, slopen etc.

**Comment by HansvanderMeij** [comment]
Helemaal mee eens.
