### ISSUE TITLE
Waarom is er nog steeds geen geometrie voor Openbare Ruimte?

### ISSUE THREAD

**Issue by SBJager** [Geonovum/IMBAG#5]
Al sinds het eerste begin van de BAG (zo'n 10 jaar geleden al weer) verwonder ik mij er over dat het object Openbare Ruimte geen geometrie heeft. Mijns insziens is dit een enorm gebrek ten aanzien van onder andere de vindbaarheid van locaties. Als ik aan bijvoorbeeld hulpdiensten de locatie moet doorgeven van een incident dat op een openbare weg of anderszins openbare ruimte heeft plaatsgevonden, maar waar geen adres in de buurt is (denk aan een provinciale weg door een bos of midden in de weilanden), dan is daar dus geen officieel authentiek object voor (natuurlijk, er zijn andere methodes voor dit voorbeeld zoals hectometerpaaltjes en dergelijke, maar dat is niet mijn punt). Bij het oorspronkelijke opzetten van een nul-bestand voor de BAG van een gemeente waar ik toentertijd voor werkte heb ik ook direct een (helaas niet-authentieke) kolom "geometrie" aan openbare ruimte toegevoegd (inititeel als aggregaat van percelen en straatnamen). Werd als zeer handig ervaren door de balie, omdat zij in 1 oogopslag konden zien of iets door de gemeente moest worden onderhouden of niet.

Ik blijf dit een gemiste kans vinden en zou graag zien dat er een geometrie voor Openbare Ruimte in de BAG opgenomen zou worden (en NIET zoals nu een "beschrijving in het brondocument", want dat is veel te vrijblijvend - nee, een echte vlakgeometrie waarvan de omtrek de grens van een openbare ruimte beschrijft).

**Comment by Dorrestijn** [comment]
Het vastleggen van de geometrie van de openbare ruimten in de BAG lijkt me inderdaad een nuttige aanvulling. Misschien is dit op korte termijn nog niet haalbaar omdat hier nadere definities moeten worden vastgesteld:
-Moet het een vlak zijn of mag het ook een lijnketen zijn
-Moeten de begrenzingen van vlakken exact op de lijnen van de BGT liggen
-Hoe om te gaan met openbare brandgangen e.d.
 Het in orde brengen van de BRT achtergrondkaart (die ook in de BAG-viewer wordt gebruikt) wordt gebruikt, zou al een mooie eerste stap zijn.

**Comment by SBJager** [comment]
> Moet het een vlak zijn of mag het ook een lijnketen zijn

Naar mijn mening een vlak. Ik denk dan met name aan het beheer van de openbare ruimte, de begrenzing van het beheer kan dan gekoppeld zijn aan deze grens. Dit verzorgt dan ook meteen een koppeling met BOR-systemen, met als groot voordeel dat het om een authentieke vastgelegde registratie gaat. Bovendien kom je met lijnen in de problemen bij pleinen en parken bijvoorbeeld. 

> Moeten de begrenzingen van vlakken exact op de lijnen van de BGT liggen

Dat is een listige. Op basis van mijn vorige punt (beheer) zou je meer denken aan het volgen van perceels- en/of beheersgrenzen, maar als je het vanuit de grondslag van een authentiek adres (vindbaarheid) bekijkt zou je zeggen dat het de lijnen van de BGT moet volgen. Het beste lijkt mij in dit geval om de praktijk te raadplegen: waar ontstaan de meeste en lastigste vraagstukken omtrent het object Openbare Ruimte, wat zijn de gekozen oplossingen in die gevallen? Daar moet wel een leidraad uit te distilleren zijn lijkt mij.

> Hoe om te gaan met openbare brandgangen e.d.

Afhankelijk van het daadwerkelijke beheer, en of deze een (straat-) naam hebben gekregen of niet. Ik ken ook gevallen waar brandgangen tussen achtererven op de percelen van de aanwonenden liggen, en dat is dus eigenlijk geen openbare ruimte, maar zijn percelen met recht van overpad (en worden dus ook niet door de betreffende gemeente onderhouden). Hier zou je ook een onderzoek kunnen uitvoeren naar wat er in de praktijk op dit moment gangbaar is, en wat een wenselijke situatie zou zijn.

> Het in orde brengen van de BRT achtergrondkaart (die ook in de BAG-viewer wordt gebruikt) wordt gebruikt, zou al een mooie eerste stap zijn.

Wat de BRT achtergrond hiermee te maken heeft begrijp ik niet direct. Deze word afgeleid uit de Top10NL en de BAG, maar de Top10NL is naar mijn mening niet geschikt als basis voor een geometrie Openbare Ruimte (schaalniveau is veel te klein - je gaat enorm veel details missen). BGT en Perceelsgrenzen lijken mij beter, en eventueel aangevuld met NWB. Beter zou andersom zijn: om het NWB uit de geometrie van de Openbare Ruimte te distilleren, dan krijg je een NWB gebaseerd op authentieke gegevens met een hoge detaillering.

Het gaat mij in deze voornamelijk om twee zaken: vindbaarheid in landelijke gebieden zonder verblijfseenheden, en beheer van openbare ruimte eenduidig vastleggen. Die twee zaken zouden enorm gebaat zijn bij een geometrie van de openbare ruimte. In het laatste geval zou je zelfs kunnen denken aan een extra veld waarmee aangegeven kan worden dat het beheer van de desbetreffende openbare ruimte aan een ander organisatie is uitbesteed dan aan de "eigenaar" (hetgeen wel voorkomt tussen bijvoorbeeld waterschappen en gemeentes).

**Comment by lodewijkjessen** [comment]
De vraag om geometrie bij de openbare ruimte op te nemen is vaker aan de orde gesteld. Naast vragen zoals welke geometrie dat zou moeten zijn (wegas als lijn, volledige verharding als vlak, bermen wel of niet, bij water ook de oever, relatie wegvak BGT?) spelen meer aspecten. Zo zijn in de BAG alleen de openbare ruimten opgenomen die door de gemeente als zodanig zijn benoemd. Als de gemeente een (deels van) een rijks- of provinciale weg niet benoemt zal die niet in de BAG worden opgenomen. Maar dit geldt ook voor andere potentiële openbare ruimten binnen de gemeente; de noodzaak die te benoemen is vanuit de BAG feitelijk alleen aanwezig als daaraan een nummeraanduiding (adres) moet worden uitgegeven.
Gebruikers hebben een bredere behoefte, die dan ook verder gaat dan de reikwijdte van de BAG. Het ministerie van IenM heeft die al enige tijd geleden onderkend. Met partijen als Rijkswaterstaat (beheerder Nationaal Wegenbestand), Geonovum, Kadaster en enkele belanghebbenden zoals de Nationale Politie en de RDW wordt verkend op welke wijze in deze informatiebehoefte kan worden voorzien. De vraag die u stelt, namelijk of er een geometrische afbakening komt van openbare ruimte, met andere woorden “van waar tot waar een straatnaam van toepassing is”, wordt daarin nadrukkelijk meegenomen.

**Comment by ArjanKloosterboer** [comment]
Dat in de BAG alleen openbare ruimten zijn opgenomen die door de gemeente zijn benoemd, zoals Lodewijk stelt, is m.i. niet bepalend voor het al dan niet opnemen van de geometrie daarvan. Het gaat er om welke informatie we van deze openbare ruimten als basisgegevens willen vaststellen. En dat is m.i. oa. de geometrie daarvan. Anders zou je je bijvoorbeeld kunnen afvragen waarom je de naam daarvan vastlegt, immers "als de gemeente een (deels van) een rijks- of provinciale weg niet benoemt zal die niet in de BAG worden opgenomen" aldus de argumentatie van Lodewijk.
Lodewijk stelt tevens dat "de noodzaak [om openbare ruimten] te benoemen is vanuit de BAG feitelijk alleen aanwezig als daaraan een nummeraanduiding (adres) moet worden uitgegeven." Dat betwijfel ik. Als type openbare ruimte kent de BAG o.a. Spoorbaan, Terrein, Kunstwerk, Landschappelijk gebied en Administratief gebied. Zijn er nummeraanduidingen langs een spoorbaan, aan een kunstwerk, etcetera? Lijkt me van niet. Verder, in de definitie noch in de toelichting van Openbare ruimte in de Catalogus BAG wordt er van gesproken dat een openbare ruimte nummeraanduidingen moet hebben. Ook dit argument lijkt me dus niet valide.
Dan meldt Lodewijk nog dat  "gebruikers hebben een bredere behoefte, die dan ook verder gaat dan de reikwijdte van de BAG". Dat zou best wel 's kunnen. Maar dat ontslaat de BAG niet van de plicht om voor de daarin aanwezige objecten de gegevens op te nemen waaraan maatschappelijk behoefte is. 
Tot slot. Om een openbare ruimte vast te kunnen stellen moet er een besluit zijn. Daaraan stelt de BAG, meen ik, een vormvereiste: er moet een kaartje bij zitten van het grondgebied waarop de openbare ruimte betrekking heeft. De geometrie van een openbare ruimte moet blijkbaar dus vastgesteld worden, in een besluit. Vreemd om die dan niet als basisgegeven vast te leggen.

**Comment by SBJager** [comment]
> Verder, in de definitie noch in de toelichting van Openbare ruimte in de Catalogus BAG wordt er van
> gesproken dat een openbare ruimte nummeraanduidingen moet hebben. Ook dit argument lijkt me
> dus niet valide.

Mee eens. En het zijn juist de openbare ruimtes die GEEN nummeraanduidingen hebben die een geometrie het beste kunnen gebruiken. Bij een nummeraanduiding zit een locatie, dus dan kun je enigszins de openbare ruimte afleiden. Maar als er geen nummeraanduidingen zijn (of als die er NOG niet zijn!), is het wel erg prettig om te weten waar die openbare ruimte dan ligt.

> Om een openbare ruimte vast te kunnen stellen moet er een besluit zijn. Daaraan stelt de BAG, meen
> ik, een vormvereiste: er moet een kaartje bij zitten van het grondgebied waarop de openbare ruimte 
> betrekking heeft. De geometrie van een openbare ruimte moet blijkbaar dus vastgesteld worden, in
> een besluit. Vreemd om die dan niet als basisgegeven vast te leggen.

Ik heb nog even lopen zoeken, maar kan het zo gauw niet terugvinden. Maar dit staat mij inderdaad ook bij, dat in het besluit een kaartje aanwezig moet zijn. Bij het opzetten van een BAG voor een gemeente heb ik er zelf dan ook direct voor gekozen om de geometrie als niet-authentiek attribuut op te nemen - je hebt het immers toch al.

**Comment by ArjanKloosterboer** [comment]
In par. 3.3.1 staat over die vormvereiste het volgende: "De gemeente dient het bij het benoemen van (nieuwe) openbare ruimten alsmede bij het wijzigen van bestaande openbare ruimten een voldoende gedetailleerde omschrijving of grafische weergave op te nemen die de ligging van de buitenruimte op enigerlei wijze aanwijst. De ligging van openbare ruimten is dus wel opgenomen in het brondocument, maar niet in de BAG-registratie." 
Dus inderdaad, wel in het besluit en niet in de registratie. Raar.
