### ISSUE TITLE
verschil WOZ - BAG t.a.v toilet in gedeelde verkeersruimte

### ISSUE THREAD

**Issue by Hilversum** [Geonovum/IMBAG#6]
Pieter, Lodewijk of collega

Twee recente uitspraken in de bijlage ivm een beroepszaak. 

Vooral de eerste bijlage : zaaknummers UTR 16 / 1806 WOZV|7, UTR 16 I 1827, UTR l6 I 1829 enUTR l6 / 1830 is van belang voor de BAG, omdat het zo haaks staat op de BAG –afbakening zoals die mede ook is vastgelegd in de notitie voor studentenhuisvesting. 

De rechtbank volgt in de kern deze redenatie. 
[Rechtbank  WOZ-Toilet - zelfstandigheid Object.pdf](https://github.com/Geonovum/IMBAG/files/552598/Rechtbank.WOZ-Toilet.-.zelfstandigheid.Object.pdf)

_5. De rechtbank stelt vast dat verweerder ter zitting heeft toegelicht dat zich in de hal bij de
woning Koningsstraat 131 een toilet bevindt dat de bewoners op de begane grond gebruiken.
Eiseres heeft ter zilting toegelicht dat er één toilet op de begane grond in de hal aanwezig is
en één toilet op de eerste verdieping. Beide toiletten bevinden zich in de gemeenschappelijke
ruimte en zijn geen onderdeel van een afsluitbare eenheid. Hierbij dient uit te worden gegaan
van de feitelijke situatie. Naar het oordeel van de rechtbank dienen Koningsstraat 131 en
Koningsstraat 133 als één object te worden beschouwd in de zin van de Wet woz. Nu de
verschillende kamers niet beschikken over een toiletruimte binnen het afsluitbare deel, kan
niet worden gezegd dat deze delen van het gebouw blijkens de indeling zijn bestemd om als
afzonderlijk geheel te worden gebruikt. Verweerder heeft het object dan ook te klein
afgebakend. De beroepsgrond slaagt._

Geen zelfstandig object dus voor de WOZ. Voor gemeentelijk praktijk is dit zeer onhandig omdat het haaks staat op de BAG redenatie. De BAG en WOZ object-afbakening lopen weer uiteen. 

Gezien de discussie op de BAG 2.0-middag over de ontsluiting via een ander VBO en de twee-over-trap-woning en de afbakening van zorg- en studentencomplexen vragen wij ons af of de huidige BAG-afbakening van verblijfsobjecten met voorzieningen bereikbaar via de gedeelde verkeersruimte, nog stand gaat houden.

Is daar wat over te zeggen??

Met vriendelijke groet
Chris van de Ven

**Comment by lodewijkjessen** [comment]
Voor de duidelijkheid eerst een korte toelichting op hoofdlijnen op de relatie tussen de BAG en de WOZ.
De BAG en de WOZ hebben zoals bekend verschillende objecten van registratie en de verhouding tussen objecten in de BAG en de WOZ is daarbij n:m; één WOZ-object kan meerdere BAG-objecten omvatten en omgekeerd kan één BAG-object meerdere WOZ-objecten omvatten. De WOZ streeft (samengevat) naar zo groot mogelijke WOZ-objecten binnen de grenzen van hetzelfde gebruik en eigendom, de BAG naar de kleinste eenheid geschikt voor zelfstandig gebruik. Meestal komt dat overeen, zeker bij woningen, maar soms ook niet.
Voor het beheer van de verschillende registraties en voor de communicatie kunnen verschillen in de afbakening nadelig zijn, maar ze zijn naar de aard onvermijdelijk. Een woning en winkel van dezelfde eigenaar die beide ook zelf gebruikt, omvat twee verblijfsobjecten, maar vormt één WOZ-object. Dat blijft zo als woning en winkel samen aan iemand anders worden verhuurd. Maar als de eigenaar in de woning blijft wonen en de winkel verhuurt worden het daarmee twee WOZ-objecten terwijl er in de BAG uiteraard niets verandert.
De WOZ is hierbij afnemer van de BAG en gebruikt onder meer de panden en verblijfsobjecten om WOZ-(deel-)objecten aan te relateren en de adressen om het WOZ-object te duiden.

Voor elke afnemende registratie, zoals de WOZ, kunnen wijzigingen in de eigen afbakening en doorwerking optreden als gevolg van onder meer gewijzigde regelgeving en van jurisprudentie.
De BAG is bij dit alles een toepassingsvrije, niet aan een specifiek afnemersproces of -belang gerelateerde basisregistratie. Voor de BAG is al in een vroeg stadium op basis van een afweging van betrokken belangen besloten om in specifieke situaties VBO’s af te bakenen waarbij de ontsluiting via een ander VBO loopt of bijvoorbeeld het toilet net buiten het eigenlijke VBO ligt (mits exclusief voor dat VBO). Dit besluit heeft onder meer te maken met het belang van het ‘hebben van een adres’ (dus: een VBO) in het maatschappelijk verkeer. 

Aanpassing van de afbakening in de BAG zoals voorgesteld zou doorwerken in onder meer de BRP, waarin alle bewoners dan zouden ‘samenwonen’, met alle gevolgen van dien. Een volgende rechterlijke uitspraak, met een wellicht wat andere uitkomst, zou in deze benadering allicht weer tot aanpassing in de BAG moeten leiden. De noodzakelijke stabiliteit en uniformiteit van de afbakening in de BAG zou daarmee geweld worden aangedaan en daarmee het karakter van de BAG als basisregistratie.
