### ISSUE TITLE
Voorzieningen bepalend bij afbakening bedrijven/kantoren!

### ISSUE THREAD

**Issue by Hilversum** [Geonovum/IMBAG#7]
De bijgevoegde uitspraak RvS (201206111/1/A3) die onlangs in de gemeente Hilversum bij een bezwaarafhandeling is gebruikt, maakt duidelijk dat afhankelijkheid van voorzieningen elders in het pand niet betekent dat er geen zelfstandig vbo is ...We kennen hierin de praktijkruimtes die afhankelijk zijn van voorzieningen die elders gelegen zijn... Deze uitspraak van de RvS kun je breder toepassen op horeca, winkels, industriefuncties etc...Voor een kantoorverzamelgebouwen geldt de uitspraak van de RvS ( 201501560/1/A3) Heerhugowaard dat er wel sprake moet zijn van voorzieningen zodat het vbo gedurende langere tijd zelfstandig kan functioneren...Het is zaak dat er onderscheid wordt gemaakt naar voorziening en bewoning, winkels, bedrijven, praktijkruimtes, bedrijfsverzamelgebouwen, kantoorverzamelgebouw, kantoorvilla's etc... Er worden in de jurisprudentie verschillende normen voor gesteld en het moet duidelijk zijn in hoeverre voorzieningen dwingend dan wel optioneel zijn. 
[RvS Tand-artsenpraktijk 201302601 1 A3.docx](https://github.com/Geonovum/IMBAG/files/568829/RvS.Tand-artsenpraktijk.201302601.1.A3.docx)

**Comment by PieterBs** [comment]
Op pagina 12 en 13 van het nieuwe handboek objectafbakening staat dit toch (deels) genoemd? Daarnaast wordt er naar mijn idee nu wel duidelijk gesproken over de afbakening van objecten waarbij van binnen naar buiten geredeneerd moet worden en waarbij je de samenhang vaststeld tussen de objecten. Maar uit je reactie lees ik af dat dit niet afdoende is?

**Comment by Hilversum** [comment]
Wat bedoel jij met het nieuwe handboek Objectafbakening?

Het gaat in de kern om het volgende.
In het Objectenhanboek 2009 is men niet expliciet over de noodzaak van voorzieningen (uniek toewijsbaar) bij de afbakening van bijv. winkels. Uit jurisprudentie blijkt dat het delen van voorziening met een aangelegen woning niet betekent dat het kantoor bij de woning niet als zelfstandig mag worden afgebakend. ..

Echter.

Bij een groot Kantoorverzamelgebouw in Heerhugowaard heeft de RvS vastgesteld dat er pas sprake is van een zelfstandige eenheid voor de BAG is, als er sprake is van zelfstandigheid qua  voorzieningen….Geen afhankelijkheden in andere ruimten. Dus voor de RvS is een deel van het kantoorverzamelgebouw pas zelfstandig voor de BAG als het zelfvoorzienend is…

Dus in het nieuwe Handboek mag, zou dit onderscheid terug moeten komen en concreet vertaald moeten worden naar winkels, bedrijfsverzamelgebouwen, kantoorvilla’s, kantoorverzamelgebouwen etc..Ik hoop dat dit duidelijker is.
