### ISSUE TITLE
Toekennen gebruiksdoel

### ISSUE THREAD

**Issue by PieterBs** [Geonovum/IMBAG#8]
Document: 20161010_BAG_gegevenscatalogus_concept_v0.4.pdf, paragraaf 3.8 blz. 15

Samenvatting:
Toekennen gebruiksdoel

Beschrijving:
In de gegevenscatalogus wordt gesproken over het toekennen van een gebruiksdoel bij het verlenen van een bouw- of omgevingsvergunning. Oftewel de bouwkundige bestemming. Er wordt niet gesproken over geconstateerde objecten en het vervolgens toekennen van gebruiksdoelen door middels van de op dat moment geldende planologische bestemming of het feitelijk gebruik? Aan het geconstateerde ligt namelijk geen brongegeven (vergunning) welke gebruikt kan worden bij het toekennen van het gebruiksdoel.

Oplossingsrichting:
Duidelijkheid geven in het objectenhandboek over het toekennen en bepalen van gebruiksdoelen bij geconstateerde objecten.

**Comment by DamirBrnobic** [comment]
Het gebruiksdoel behoeft wat mij betreft ook speciale aandacht. Het huidige objectenhandboek geeft als brondocumentoptie alleen de omgevingsvergunning. De nieuwe (concept-)gegevenscatalogus voegt hieraan toe dat "[o]p een later moment [..] de door een gemeente geformaliseerde gebruikswijziging als basis [kan] dienen voor wijziging of opname van een aanvullend gebruiksdoel."

Wat mij betreft schept bovengenoemde zin niet genoeg duidelijkheid, omdat "geformaliseerd" in de praktijk moeilijk toepasbaar is voor medewerkers zonder juridische achtergrond. Oplossing: uitputtende lijst of duidelijkere omschrijving van brondocumenten opnemen waarmee gebruiksdoelen aangepast mogen worden. Uit de catalogus moet duidelijk af te leiden zijn of in de praktijk alleen besluiten gebruikt mogen worden of ook schriftelijke verklaringen. 

Tot slot blijft er een spanningsveld bestaan tussen feitelijk en vergund/geformaliseerd gebruik. Bijvoorbeeld: wat doen we als bij een agrarisch object, waarbij het tweede gebruiksdoel 'industriefunctie' van de woning bestaat bij de gratie van de stal, diezelfde stal wordt gesloopt en de woning blijft staan? Dan is de industriefunctie 'gesloopt', maar wordt er geen besluit of vergunning opgesteld. Is het dan niet wenselijk om toch met een schriftelijke verklaring het twee gebruiksdoel 'industriefunctie' af te voeren bij de voormalige bedrijfswoning? En zo ja, kijken we daarmee dan niet stiekem toch een beetje naar de feitelijke situatie? Oplossing: lijst met uitzonderingen opnemen waarbij toch naar de feitelijke situatie gekeken wordt (mantelzorg in vrijstaande garage, sloop stal bij agrarisch object, etc.).

**Comment by JeroenRijkse** [comment]
Ik vind het ook wenselijk dat hier nog eens naar gekeken wordt.
In mijn gemeente wordt wekelijks een bestand gegenereerd waarbij er in twee registraties gekeken wordt.
Indien er in de BRP een inschrijving is op een adres zonder woonfunctie (ontleend aan de gebruiksfunctie van het bijbehorende BAG verblijfsobject) dan krijg ik dit adres ter controle aangeboden.
Ook zijn de balie/service medewerkers geïnstrueerd om bij inschrijvingen op niet-woningen een melding te maken bij de BAG beheerder.
De BAG beheerder toetst de locatie aan het bestemmingsplan en maakt een melding bij de vergunning toetsers van bouw en woningtoezicht. Krijgt de BAG beheerder groen licht dan wordt er een extra gebruiksfunctie voor de woonfunctie opgevoerd.
Problematischer zijn de niet woningen. Indien de eigenaar besluit om in een kantoorfunctie een winkel te beginnen dan hoeft er geen omgevingsvergunning voor aangevraagd te worden. Dit als voorbeeld.
Het bestemmingsplan kent veelal meerdere functies toe op een locatie.
En wat vind de afnemer eigenlijk belangrijk? Het vergunde gebruik? Of, toch het feitelijke gebruik?
Graag een aanpassing voor het registreren van de gebruiksfunctie van een verblijfsobject.
